/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Panels;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Business.Business;
import model.ProductManagement.Product;
import model.Supplier.Supplier;

/**
 *
 * @author Poojith K
 */
public class AdjustPricesPanel extends javax.swing.JPanel {
    private Business business;
    private BrowsePricePanel browsePricePanel;
    private SimulationPanel simulationPanel;
    private MaximizeProfitPanel maximizeProfitPanel;
    private FinalReportPanel finalReportPanel;
    /**
     * Creates new form AdjustPricesPanel
     */
    public AdjustPricesPanel(Business business, SimulationPanel simulationPanel, MaximizeProfitPanel maximizeProfitPanel,
                             BrowsePricePanel browsePricePanel, FinalReportPanel finalReportPanel) {
        this.business = business;
        this.simulationPanel = simulationPanel;
        this.maximizeProfitPanel = maximizeProfitPanel;
        this.browsePricePanel = browsePricePanel;
        this.finalReportPanel = finalReportPanel;
        initComponents();
        ModeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lower Prices", "Higher Prices" }));
        populateTable("Lower Prices");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AdjustPricesTable = new javax.swing.JTable();
        ModeComboBox = new javax.swing.JComboBox<>();
        ApplyAdjustmentsBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        AdjustPricesTable.setBackground(new java.awt.Color(102, 204, 255));
        AdjustPricesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Supplier Name", "Actual Price", "Target Price", "Sales Frequency (Above/Below Target)", "Suggested New Price"
            }
        ));
        jScrollPane1.setViewportView(AdjustPricesTable);

        ModeComboBox.setBackground(new java.awt.Color(102, 204, 255));
        ModeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ModeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeComboBoxActionPerformed(evt);
            }
        });

        ApplyAdjustmentsBtn.setBackground(new java.awt.Color(102, 204, 255));
        ApplyAdjustmentsBtn.setText("Apply Adjustments");
        ApplyAdjustmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyAdjustmentsBtnActionPerformed(evt);
            }
        });

        SaveBtn.setBackground(new java.awt.Color(102, 204, 255));
        SaveBtn.setText("Save Changes");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(ApplyAdjustmentsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ApplyAdjustmentsBtn, SaveBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ApplyAdjustmentsBtn))
                    .addComponent(SaveBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ApplyAdjustmentsBtn, SaveBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void ModeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedMode = ModeComboBox.getSelectedItem().toString();
        populateTable(selectedMode);
    }//GEN-LAST:event_ModeComboBoxActionPerformed

    private void ApplyAdjustmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyAdjustmentsBtnActionPerformed
        // TODO add your handling code here:
        applyAdjustments();
    }//GEN-LAST:event_ApplyAdjustmentsBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        saveChanges();
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AdjustPricesTable;
    private javax.swing.JButton ApplyAdjustmentsBtn;
    private javax.swing.JComboBox<String> ModeComboBox;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}


