/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Panels;

import java.util.function.Supplier;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Business.Business;
import model.ProductManagement.Product;
import model.Supplier.Supplier;

/**
 *
 * @author omraut
 */
public class FinalReportPanel extends javax.swing.JPanel {

    private Business business;

    /**
     * Creates new form FinalReportPanel
     */
    public FinalReportPanel(Business business) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FinalReportTable = new javax.swing.JTable();
        GenerateReportBtn = new javax.swing.JButton();
        ResetReportBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        FinalReportTable.setBackground(new java.awt.Color(102, 204, 255));
        FinalReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Original Target Price", "Adjusted Target Price", "Sales Below Target", "Sales Above Target", "Revenue Before Adjustment", "Revenue After Adjustment"
            }
        ));
        jScrollPane1.setViewportView(FinalReportTable);

        GenerateReportBtn.setBackground(new java.awt.Color(102, 204, 255));
        GenerateReportBtn.setText("Generate Report");
        GenerateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportBtnActionPerformed(evt);
            }
        });

        ResetReportBtn.setBackground(new java.awt.Color(102, 204, 255));
        ResetReportBtn.setText("Reset Report");
        ResetReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(GenerateReportBtn)
                        .addGap(42, 42, 42)
                        .addComponent(ResetReportBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {GenerateReportBtn, ResetReportBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateReportBtn)
                    .addComponent(ResetReportBtn))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {GenerateReportBtn, ResetReportBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void GenerateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportBtnActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_GenerateReportBtnActionPerformed

    private void ResetReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetReportBtnActionPerformed
        // TODO add your handling code here:
        resetReport();
    }//GEN-LAST:event_ResetReportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FinalReportTable;
    private javax.swing.JButton GenerateReportBtn;
    private javax.swing.JButton ResetReportBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


}
